@baseURL = http://localhost:4000/api/logins
POST {{baseURL}}/cadastro
Content-Type: application/json

{
    "nome": "Nome do Usuário",
    "email": "teste@teste.com",
    "senha": "@teste123"
}
###
POST {{baseURL}}/
Content-Type: application/json

{
    "email": "teste@teste.com",
    "senha": "@teste123"
}