@baseURL = http://localhost:4000/api/logins
POST {{baseURL}}/cadastro
Content-Type: application/json

{
    "nome": "Administrador",
    "email": "admin@admin.com",
    "senha": "admin123"
}
###
POST {{baseURL}}/
Content-Type: application/json

{
    "email": "teste@teste.com",
    "senha": "@teste123"
}