@baseURL = http://localhost:4000/api/products


GET {{baseURL}}/?limit=3&skip=0
Content-Type: application/json
access-token: 

###
GET {{baseURL}}/all
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY2N2ExYmUwNTZkNDIyMDFhZTQwNzEiLCJpYXQiOjE3MTc5OTIxOTUsImV4cCI6MTcxODA3ODU5NX0.ZzjR13Ad0gEemT2r1KkTNhOi304F1n6YtCIFZ5_1j1c

###
POST {{baseURL}}
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjZhMmRlYzNhYTFhZjFkYmU0MjQyYTQiLCJpYXQiOjE3MTgyMzQ2MjAsImV4cCI6MTcxODMyMTAyMH0.C_shUAnUESD6PnSs007wjwiytTEk26WeMVsZ-H7-Naw

{
    "nome": "Impressora Laser Multifuncional",
    "tipo": "material-permanente",
    "quantidade": 5,
    "categoria": "material-de-escritorio-especializado",
    "descricao": "Impressora multifuncional para o departamento administrativo"
}

###
DELETE {{baseURL}}/6639171fda80f9cc4adaa803
Content-Type: application/json
access-token:

###
PUT {{baseURL}}
Content-Type: application/json
access-token:

{
    "_id": "6623bcd6c7fb6560f205bd46",
    "nome": "Caneta Esferografica Vermelha",
    "quantidade": 2,
    "preco": 5.05,
    "descricao": "Caneta Esferografica Vermelha",
    "data": "2024-04-11T23:25:05.852Z"
}
###
GET {{baseURL}}/filtros/?qtdMin=1&qtdMax=4&precoMin=40&precoMax=50
Content-Type: application/json
access-token:
###
